const mongoose=require('mongoose')

const UserModel=mongoose.Schema({
    name:{
        type:String,
        required:true
    },
    email:{
        type:String,
        required:true,
        unique:true
    },
    picutre:{
        type:String
    },
    number:{
        type:String,
        required:true
    },
    DOB:{
        type:String,
        required:true
    },
    gender:{
        type:String,
        required:true
    },
    password:{
        type:String,
        required:true
    },
    isloggedin:{
        type:Boolean,
        default:true
    },
    interests:{
        type:[String]
    },
    posts:{
        type:[mongoose.Schema.Types.ObjectId],
        ref:"posts"
    },
    followers:{
        type:[mongoose.Schema.Types.ObjectId],
        ref:"users"
    },
    following:{
        type:[mongoose.Schema.Types.ObjectId],
        ref:"users"
    },
    contribution:{
        type:Number,
        default:0
    },
    description:{
        type:String
    },
    address:{
        type:String
    },
    created_date:{
        type:Date,
        default:Date.now()
    }

})

module.exports=mongoose.model('users',UserModel)